version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000"
    volumes:
      - backend_data:/app/public/images
    environment:
      - PORT=4000
      - DB_CONNECT=mongodb://mongodb:27017/web_class
      - SERVER_TOKEN_SECRET=${SERVER_TOKEN_SECRET}
      - TOKEN_EXPIRES=${TOKEN_EXPIRES}
      - REFRESH_TOKEN_EXPIRES=${REFRESH_TOKEN_EXPIRES}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_ADDRESS=${GOOGLE_REDIRECT_ADDRESS}
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data:
  backend_data:
