/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Web Dev 2025 REST API
 * REST server including authentication using JWT by Roy Canani & Urir Shiber
 * OpenAPI spec version: 1.0.0
 */

export * from './authLogin';
export * from './authRegister';
export * from './authResponse';
export * from './postAuthLogoutBody';
export * from './postAuthRefreshBody';
export * from './user';